# Generated by Django 4.1.7 on 2023-03-22 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pictures.models
import songuploader.utils


class Migration(migrations.Migration):
    replaces = [
        ("imageupload", "0001_initial"),
        ("imageupload", "0002_alter_userimage_changed_at_and_more"),
        ("imageupload", "0003_alter_userimage_image"),
        ("imageupload", "0004_userimage_height_userimage_width_and_more"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "image_type",
                    models.IntegerField(
                        choices=[(0, "Picture"), (1, "Baby Picture")],
                        verbose_name="Image Type",
                    ),
                ),
                (
                    "image",
                    pictures.models.PictureField(
                        aspect_ratios=[None, "1/1", "3/2"],
                        breakpoints={
                            "l": 1200,
                            "m": 992,
                            "s": 768,
                            "xl": 1400,
                            "xs": 576,
                        },
                        container_width=1200,
                        file_types=["WEBP"],
                        grid_columns=12,
                        height_field="height",
                        pixel_densities=[1, 2],
                        upload_to=songuploader.utils.generate_filename,
                        verbose_name="Image",
                        width_field="width",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=512, verbose_name="description"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now=True, verbose_name="Changed at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                ("height", models.IntegerField(default=100)),
                ("width", models.IntegerField(default=100)),
            ],
            options={
                "verbose_name": "User Image",
                "verbose_name_plural": "User Images",
            },
        ),
    ]
