# Generated by Django 4.1.7 on 2023-03-20 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pictures.models
import songuploader.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, verbose_name="Created at"),
                ),
                (
                    "image_type",
                    models.IntegerField(
                        choices=[(0, "Picture"), (1, "Baby Picture")],
                        verbose_name="Image Type",
                    ),
                ),
                (
                    "image",
                    pictures.models.PictureField(
                        aspect_ratios=[None],
                        breakpoints={
                            "l": 1200,
                            "m": 992,
                            "s": 768,
                            "xl": 1400,
                            "xs": 576,
                        },
                        container_width=1200,
                        file_types=["WEBP"],
                        grid_columns=12,
                        pixel_densities=[1, 2],
                        upload_to=songuploader.utils.generate_filename,
                        verbose_name="Image",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=512, verbose_name="description"),
                ),
                ("changed_at", models.DateTimeField(verbose_name="Changed at")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Image",
                "verbose_name_plural": "User Images",
            },
        ),
    ]
