# Generated by Django 4.1.7 on 2023-03-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imageupload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userimage",
            name="changed_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Changed at"),
        ),
        migrations.AlterField(
            model_name="userimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
    ]
