# Generated by Django 4.1.7 on 2023-03-22 08:23

from django.db import migrations
import pictures.models
import pictures.migrations as picmigrations
import songuploader.utils


class Migration(migrations.Migration):
    dependencies = [
        ("imageupload", "0002_alter_userimage_changed_at_and_more"),
    ]

    operations = [
        picmigrations.AlterPictureField(
            model_name="userimage",
            name="image",
            field=pictures.models.PictureField(
                aspect_ratios=[None, "1/1", "3/2"],
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                pixel_densities=[1, 2],
                upload_to=songuploader.utils.generate_filename,
                verbose_name="Image",
            ),
        ),
    ]
