# Generated by Django 4.1.7 on 2023-03-22 08:48

from django.db import migrations, models
import pictures.models
import pictures.migrations as picmigrations
import songuploader.utils


class Migration(migrations.Migration):
    dependencies = [
        ("imageupload", "0003_alter_userimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userimage",
            name="height",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userimage",
            name="width",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        picmigrations.AlterPictureField(
            model_name="userimage",
            name="image",
            field=pictures.models.PictureField(
                aspect_ratios=[None, "1/1", "3/2"],
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                height_field="height",
                pixel_densities=[1, 2],
                upload_to=songuploader.utils.generate_filename,
                verbose_name="Image",
                width_field="width",
            ),
        ),
    ]
