# Generated by Django 4.1.7 on 2023-03-22 22:04

from django.db import migrations, models
import pictures.models
import songuploader.utils


class Migration(migrations.Migration):
    dependencies = [
        (
            "imageupload",
            "0001_initial_squashed_0004_userimage_height_userimage_width_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motto", models.CharField(max_length=128, verbose_name="My Motto")),
                (
                    "favorite_teacher",
                    models.CharField(max_length=64, verbose_name="Favorite Teacher"),
                ),
                (
                    "favorite_subject",
                    models.CharField(max_length=64, verbose_name="Favorite Subject"),
                ),
                (
                    "things_missed",
                    models.CharField(max_length=256, verbose_name="Things I will miss"),
                ),
                (
                    "things_not_missed",
                    models.CharField(
                        max_length=256, verbose_name="Things I will not miss"
                    ),
                ),
                (
                    "cant_live_without",
                    models.CharField(
                        max_length=256, verbose_name="Things I can't live without"
                    ),
                ),
                (
                    "expulsion",
                    models.CharField(max_length=128, verbose_name="Expulsions ans why"),
                ),
                (
                    "favorite_song",
                    models.CharField(max_length=64, verbose_name="Favorite Song"),
                ),
                (
                    "celebrity_crush",
                    models.CharField(max_length=32, verbose_name="Celebrity Crush"),
                ),
                (
                    "lower_level_crush",
                    models.CharField(max_length=32, verbose_name="Lower Level Crush"),
                ),
                (
                    "best_school_experience",
                    models.CharField(
                        max_length=64, verbose_name="Best School Experience"
                    ),
                ),
                (
                    "worst_school_experience",
                    models.CharField(
                        max_length=64, verbose_name="Worst School Experience"
                    ),
                ),
                (
                    "school_thing_needed",
                    models.CharField(
                        max_length=64,
                        verbose_name="Without that I would not have survived the school",
                    ),
                ),
                (
                    "abi_learned",
                    models.CharField(
                        max_length=64,
                        verbose_name="This is what I learned during my Abi",
                    ),
                ),
                (
                    "after_abi",
                    models.CharField(
                        max_length=128, verbose_name="What I will do after graduation"
                    ),
                ),
                (
                    "additional_info",
                    models.CharField(max_length=512, verbose_name="Additional Info"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="userimage",
            name="height",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="userimage",
            name="image",
            field=pictures.models.PictureField(
                aspect_ratios=[None, "1/1", "3/4"],
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                height_field="height",
                pixel_densities=[1, 2],
                upload_to=songuploader.utils.generate_filename,
                verbose_name="Image",
                width_field="width",
            ),
        ),
        migrations.AlterField(
            model_name="userimage",
            name="width",
            field=models.IntegerField(),
        ),
    ]
