# Generated by Django 4.1.7 on 2023-03-22 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "imageupload",
            "0005_profile_alter_userimage_height_alter_userimage_image_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userimage",
            name="description",
        ),
    ]
