# Generated by Django 4.1.7 on 2023-03-22 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("imageupload", "0006_remove_userimage_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="abi_learned",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="This is what I learned during my Abi",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="additional_info",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Additional Info"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="after_abi",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="What I will do after graduation",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="best_school_experience",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Best School Experience",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cant_live_without",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Things I can't live without",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="celebrity_crush",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Celebrity Crush"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="expulsion",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Expulsions ans why"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="favorite_song",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Favorite Song"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="favorite_subject",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Favorite Subject"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="favorite_teacher",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Favorite Teacher"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="lower_level_crush",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Lower Level Crush"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="motto",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="My Motto"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="school_thing_needed",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Without that I would not have survived the school",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="things_missed",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Things I will miss"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="things_not_missed",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Things I will not miss",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="worst_school_experience",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Worst School Experience",
            ),
        ),
    ]
