version: '3'

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"

    volumes:
      - my-db:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  web:
    build: .
    ports:
      - "8080:80"
      - "3000:3000"
    expose:
      - 80
    restart: unless-stopped
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 30s
      timeout: 10s
      retries: 5

    volumes:
      - ./src/:/app/web/.
      - ./.env:/app/web/.

volumes:
  my-db:


