[tool.poetry]
name = "song-uploader"
version = "0.1.0"
description = ""
authors = ["Simon Felix Seeger <simon.f.seeger@gmx.de>"]
readme = "README.md"
package-mode = false


[tool.poetry.dependencies]
python = "^3.13"
Django = "^6.0.5"
python-dotenv = "^1.2.2"
mysqlclient = "^2.2.8"
django-crispy-forms = "^2.6"
crispy-bulma = "0.9.0"
debugpy = "^1.8.20"
requests = "^2.34.2"
gunicorn = "^26.0.0"
tqdm = "^4.67.3"
django-prometheus = "^2.4.1"
django-extensions = "^4.1"
django-cleanup = "^9.0.0"
django-dbbackup = "^5.3.0"
django-filter = "^25.2"
django-pictures = "^1.7.5"
django-tinymce = "^5.0.0"
bleach = {extras = ["css"], version = "^6.3.0"}
yt-dlp = "^2026.3.17"
pandas = "^3.0.3"
django-q2 = "^1.10.0"
django-compressor = "^4.6.0"

[tool.poetry.group.dev.dependencies]
pylance = "^6.0.1"
black = "^26.5.1"
pylint-django = "^2.7.0"
ansible = "^13.7.0"
coverage = "^7.14.0"
pandas-stubs = "~=3.0.3"

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
