# Generated by Django 4.1.7 on 2023-03-04 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uploader.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_url", models.CharField(max_length=512, verbose_name="Song URL")),
                (
                    "start_time",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Start Time"
                    ),
                ),
                (
                    "song",
                    models.FileField(
                        upload_to=uploader.models.generate_filename,
                        verbose_name="Song File",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
