# Generated by Django 4.1.7 on 2023-03-05 12:43

import django.core.validators
from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="song",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=uploader.models.generate_filename,
                validators=[
                    django.core.validators.FileExtensionValidator(["mp3", "wav", "ogg"])
                ],
                verbose_name="Song File",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="song_url",
            field=models.URLField(
                blank=True, max_length=512, null=True, verbose_name="Song URL"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="start_time",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Start Time",
            ),
        ),
    ]
