# Generated by Django 4.2.21 on 2025-05-29 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_alter_submission_end_time_alter_submission_song_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='end_time',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='End Time'),
        ),
    ]
