# Generated by Django 4.2.1 on 2023-05-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_alter_imageanswervalue_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="end_date",
            field=models.DateField(verbose_name="End Date"),
        ),
    ]
