# Generated by Django 4.2.1 on 2023-05-21 10:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0005_alter_poll_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="question",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="Description"),
        ),
    ]
