# Generated by Django 4.2.1 on 2023-06-02 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0006_alter_poll_description_alter_question_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["position", "name"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
    ]
