# Generated by Django 4.2.1 on 2023-06-02 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0007_alter_question_options_question_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["position", "created_at", "name"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
    ]
