# Generated by Django 4.2.1 on 2023-06-13 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0009_alter_imageanswervalue_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
