# Generated by Django 4.2.3 on 2023-09-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0010_response_created_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["content_type", "answer_value_id"],
                name="polls_answe_content_fe9703_idx",
            ),
        ),
    ]
