# Generated by Django 4.2.21 on 2025-05-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_answer_polls_answe_content_fe9703_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='polls_answe_content_fe9703_idx',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answer_value_id',
            new_name='object_id',
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['content_type', 'object_id'], name='polls_answe_content_459135_idx'),
        ),
    ]
