---
- name: Installing required packages
  apt:
    pkg:
      - fail2ban
      - sendmail
    state: latest
    update_cache: true

- name: Copy Config
  template:
    src: "templates/jail.local.j2"
    dest: "/etc/fail2ban/jail.local"

- name: Copy Login Filter
  template:
    src: "templates/django_login.conf.j2"
    dest: "/etc/fail2ban/filter.d/django_login.conf"

- name: Copy Reset Filter
  template:
    src: "templates/django_reset.conf.j2"
    dest: "/etc/fail2ban/filter.d/django_reset.conf"

- name: Enable fail2ban
  service:
    name: fail2ban
    enabled: true
    state: started
  notify:
    - fail2ban restart
