- name: pull branch main
  git:
    repo: "{{ repo }}"
    dest: "{{ repo_dir }}"
    accept_hostkey: yes
    force: yes
    version: "{{ branch_name | default('main', true) }}"

- name: install virtualenv
  pip:
    name: virtualenv

- name: install python requirements
  pip:
    requirements: "{{ repo_dir }}/requirements.txt"
    virtualenv: "{{repo_dir}}/.venv"

- name: Install npm packages
  npm:
    path: "{{repo_dir}}/src/theme"

- name: create static_root dir
  file: path={{ static_dir }} state=directory mode=755

- name: create media_root dir
  file: path={{ media_dir }} state=directory mode=755

- name: create backup dir
  file: path={{ backup_dir }} state=directory mode=750

- name: change perms on app directory
  file:
    path: "{{repo_dir}}"
    owner: gunicorn
    group: www-data
    recurse: yes

- name: include vault
  include_vars:
    file: vault.yml

- name: create dotenv
  template:
    src: "templates/.env.j2"
    dest: "{{ django_dir }}/.env"

- name: django collectstatic
  shell: "{{python_path}} manage.py collectstatic --noinput chdir={{ django_dir }}"

- name: change perms on static directory
  file:
    path: "{{ static_dir }}"
    owner: gunicorn
    group: www-data
    recurse: yes

- name: django compilemessages
  shell: "{{python_path}} manage.py compilemessages chdir={{ django_dir }}"

- name: django migrate
  shell: "{{python_path}} manage.py migrate --noinput chdir={{ django_dir }}"
  notify:
    - daemon-reload
    - gunicorn restart

- name: create qcluster procfile
  template:
    src: "templates/qcluster.service.j2"
    dest: "/etc/systemd/system/qcluster.service"
  notify:
    - daemon-reload

- name: Enable qcluster
  service:
    name: qcluster.service
    enabled: true
    state: started
  notify:
    - qcluster restart
