- name: pull branch
  git:
    repo: "{{ repo }}"
    dest: "{{ repo_dir }}"
    accept_hostkey: yes
    force: yes
    version: "{{ branch_name | default('main', true) }}"

- block:
    - name: download python 
      get_url:
        url: https://www.python.org/ftp/python/3.11.6/Python-3.11.6.tgz
        dest: /usr/src/Python-3.11.6.tgz
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2

    - name: unpack python binaries
      unarchive:
        src: "/usr/src/Python-3.11.6.tgz"
        remote_src: yes
        dest: "/usr/src"
        creates: "/usr/src/Python-3.11.6"

    - name: configure python
      shell:
        cmd: ./configure --enable-optimizations
        chdir: /usr/src/Python-3.11.6/
      become: true
    
    - name: compile python
      shell:
        cmd: make install
        chdir: /usr/src/Python-3.11.6/
      become: true
  when:
    - not python_skip_install

- name: install virtualenv
  pip:
    name: virtualenv

- name: install python requirements
  pip:
    requirements: "{{ repo_dir }}/requirements.txt"
    virtualenv: "{{repo_dir}}/.venv"
    virtualenv_python: "python3.11"

- name: Install npm packages
  npm:
    path: "{{repo_dir}}/src/theme"

- name: create static_root dir
  file: path={{ static_dir }} state=directory mode=774 recurse=yes

- name: create media_root dir
  file:
    path: "{{ media_dir }}"
    state: directory
    mode: 0760
    owner: gunicorn
    group: gunicorn
    recurse: yes

- name: create backup dir
  file:
    path: "{{ backup_dir }}"
    state: directory
    mode: 0760
    owner: gunicorn
    group: gunicorn
    recurse: yes

- name: create log dir
  file:
    path: "{{ log_dir }}"
    state: directory
    mode: 0760
    owner: gunicorn
    group: gunicorn
    recurse: yes

- name: change perms on app directory
  file:
    path: "{{repo_dir}}"
    owner: gunicorn
    group: gunicorn
    recurse: yes

- name: include vault
  include_vars:
    file: vault.yml

- name: create dotenv
  template:
    src: "templates/.env.j2"
    dest: "{{ django_dir }}/.env"

- name: django collectstatic
  shell: "{{python_path}} manage.py collectstatic --noinput chdir={{ django_dir }}"

- name: change perms on static directory
  file:
    path: "{{ static_dir }}"
    owner: gunicorn
    group: www-data
    recurse: yes

- name: django compilemessages
  shell: "{{python_path}} manage.py compilemessages --use-fuzzy chdir={{ django_dir }}"

- name: django migrate
  shell: "{{python_path}} manage.py migrate --noinput chdir={{ django_dir }}"
  notify:
    - daemon-reload
    - gunicorn restart

- name: create qcluster procfile
  template:
    src: "templates/qcluster.service.j2"
    dest: "/etc/systemd/system/qcluster.service"
  notify:
    - daemon-reload

- name: Enable qcluster
  service:
    name: qcluster.service
    enabled: true
    state: started
  notify:
    - qcluster restart
