- name: create log dir
  file:
    path: "{{ log_dir }}"
    state: directory
    owner: gunicorn
    group: gunicorn
    mode: 0760
    recurse: yes

- name: create procfile
  template:
    src: "templates/gunicorn.service.j2"
    dest: "/etc/systemd/system/gunicorn.service"

- name: create socket
  template:
    src: "templates/gunicorn.socket.j2"
    dest: "/etc/systemd/system/gunicorn.socket"

- name: Enable gunicorn
  service:
    name: gunicorn.service
    enabled: true
    state: started
  notify:
    - gunicorn restart

- name: Enable gunicorn socket
  service:
    name: gunicorn.socket
    enabled: true
    state: started
  notify:
    - gunicorn restart
