---
- name: include vault
  include_vars:
    file: vault.yml

- name: Create group
  group:
    name: "gunicorn"
    state: present

- name: Create Users Task
  user:
    name: "{{ item }}"
    state: present
    password: "{{ default_password | password_hash('sha512','A512') }}"
    shell: /bin/bash
    group: "gunicorn"
    system: yes
  loop:
    - gunicorn
