- name: setup project on host
  hosts: all
  remote_user: ubuntu
  become: yes

  roles:
    - {role: apt, become: yes, tags: "apt"}
    - {role: gunicorn, become: yes, tags: "gunicorn"}
    - {role: nginx, tags: "nginx"}
    - {role: django, tags: "django"}
