- name: setup mysql database
  hosts: mysql
  remote_user: ansible
  become: yes

  roles:
    - {role: mysql, become: yes, tags: "mysql"}

- name: setup project on host
  hosts: web
  remote_user: ansible
  become: yes

  roles:
    - {role: apt, become: yes, tags: ["web", "rerun"]}
    - {role: user_creation, become: yes, tags: "web"}
    - {role: gunicorn, become: yes, tags: ["web", "rerun"]}
    - {role: nginx, become: yes, tags: ["web", "rerun"]}

    - {role: grafana, become: yes, tags: ["web", "monitoring"]}
    - {role: prometheus, become: yes, tags: ["web", "monitoring"]}
    - {role: node_exporter, become: yes, tags: ["web", "monitoring"]}
    
    - {role: django, tags: ["web", "rerun"]}
    - {role: fail2ban, tags: ["web", "rerun", "fail2ban"]}
