- name: setup project on host
  hosts: all
  remote_user: ansible
  become: yes

  roles:
    - {role: apt, become: yes, tags: "apt"}
    - {role: gunicorn, become: yes, tags: "gunicorn"}
    - {role: nginx, become: yes, tags: "nginx"}
    # - {role: prometheus, become: yes, tags: "prometheus"}
    # - {role: node_exporter, become: yes, tags: "node_exporter"}
    - {role: django, tags: "django"}
