- name: Running apt update
  apt: update_cache=yes

- name: Installing required packages
  apt:
    pkg:
      - git
      - python3-pip
      - nginx
      - gettext
      - default-libmysqlclient-dev
      - default-mysql-client
      - curl
      - nodejs
      - npm
      - apt-transport-https
      - software-properties-common
      - wget
      - ffmpeg
    state: latest
    update_cache: true
