- name: Running apt update
  apt: update_cache=yes

- name: Installing required packages
  apt:
    pkg:
      - git
      - python3-pip
      - nginx
      - gettext
      - default-libmysqlclient-dev
      - default-mysql-client
      - curl
      - nodejs
      - npm
      - apt-transport-https
      - software-properties-common
      - wget
      - ffmpeg
      - build-essential 
      - gdb
      - lcov
      - pkg-config
      - libbz2-dev 
      - libffi-dev 
      - libgdbm-dev 
      - libgdbm-compat-dev 
      - liblzma-dev 
      - libncurses5-dev 
      - libreadline6-dev 
      - libsqlite3-dev 
      - libssl-dev
      - lzma
      - lzma-dev 
      - tk-dev
      - uuid-dev
      - zlib1g-dev
    state: latest
    update_cache: true
