name: Deploy
on:
  push:
    branches: ["main", "deployment"]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@master

      - name: create files
        run: echo {{secrets.VAULT_PASS}} > ansible/.vault_pass

      - name: run ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/site.yml
          key: ${{secrets.SSH_KEY}}
          options: -i hosts
