name: Deploy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@master

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: create files
        run: |
          touch ansible/.vault_pass
          echo "${{secrets.VAULT_PASS}}" > ansible/.vault_pass
          ls -lah
          ls -lah ansible

      - name: run ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/site.yml
          key: ${{secrets.SSH_KEY}}
          options: |
            --inventory ansible/hosts
            --limit web
            --tags "rerun"
            --extra-vars "ansible_sudo_pass=${{secrets.SUDO_PASSWD}} branch_name=${{ steps.extract_branch.outputs.branch }}"
            --vault-password-file "ansible/.vault_pass"
