name: Deploy
on:
  push:
    branches: ["main"]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: run deploy script
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export SECRET_KEY=${{ secrets.SECRET_KEY }}
            export MYSQL_DB=${{ secrets.MYSQL_DB }}
            export MYSQL_USER=${{ secrets.MYSQL_USER }}
            export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            pkill gunicorn
            ./home/gunicorn/Abitur-Song-Uploader/deploy/scripts/deploy.sh
            ./home/gunicorn/Abitur-Song-Uploader/deploy/scripts/django_setup.sh
