name: Deploy
on:
  push:
    branches: ["main", "deployment"]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@master

      - name: create files
        run: |
          touch ansible/.vault_pass
          echo "${{secrets.VAULT_PASS}}" > ansible/.vault_pass

      - name: run ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/site.yml
          key: ${{secrets.SSH_KEY}}
          options: |
            --inventory ansible/hosts
            --extra-vars "ansible_sudo_pass=${{secrets.SUDO_PASSWD}}"
            --verbose
